// Meta package: Phase 1a stable exports (GSAP + effects + config).

export {
  useGSAP,
  type UseGSAPCallback,
  type UseGSAPOptions,
  type UseGSAPReturn,
  GSAPTimeline,
  type GSAPTimelineProps,
  GSAPFrom,
  type GSAPFromProps,
  GSAPTo,
  type GSAPToProps,
  GSAPSequence,
  type GSAPSequenceProps,
  registerAllGSAPPlugins,
  registerMorphSVGPlugin,
  registerSplitTextPlugin,
  registerDrawSVGPlugin,
  isPluginRegistered,
  assertPluginRegistered,
  PluginNotRegisteredError,
  type GSAPPluginName,
  MorphSVGPlugin,
  ensureMorphSVGPluginRegistered,
  morphSVG,
  type MorphSVGValue,
  DrawSVGPlugin,
  ensureDrawSVGPluginRegistered,
  drawSVG,
  type DrawSVGValue,
  SplitText,
  ensureSplitTextPluginRegistered,
  createSplitText,
} from "@remotion-reloaded/gsap";

export {
  Effect,
  EffectStack,
  EffectPreset,
  getAvailableEffectTypes,
  resolveEffectPlan,
  type EffectProps,
  type EffectStackProps,
  type EffectType,
  type EffectPresetProps,
  type PresetName,
} from "@remotion-reloaded/effects";

export {
  withReloaded,
  type WithReloadedOptions,
  type ReloadedConfig,
  getRenderEnvironment,
  type RenderEnvironment,
  useRenderMode,
  type RenderMode,
  checkCompatibility,
  type CompatibilityResult,
  setErrorMode,
  getErrorMode,
  handleError,
  type ErrorMode,
  framesToSeconds,
  secondsToFrames,
} from "@remotion-reloaded/config";
